In [60]:
#Загрузка набора данных
import pandas as pd
df = pd.read_csv("combined_data.csv")
df.head()

,Car Model,Condition,Mileage,Price (USD),Monthly Payment,Dealer Name
0,2023 BMW M2 Base,Used,"2,496 mi.","$63,000","Est. $1,184/mo",Murgado Ford of Chicago
1,2020 Dodge Charger SXT,Used,"98,302 mi.","$14,995",Est. $282/mo,Blue Sky Auto Sales - Brighton Park
2,2016 Scion iM Base,Used,"72,040 mi.","$12,690",Est. $239/mo,Mcgrath Evanston Subaru
3,2022 Volvo XC60 Recharge Plug-In Hybrid T8 Ins...,Used,"31,580 mi.","$38,998",Est. $733/mo,CarMax Birmingham
4,2012 Mitsubishi Lancer SE,Used,"54,197 mi.","$9,995",Est. $188/mo,Moto Zone Inc.

In [61]:
#Подсчет пустых строк
print(df.isnull().sum())

Car Model             0
Condition            28
Mileage            5143
Price (USD)           0
Monthly Payment     200
Dealer Name           0
dtype: int64

In [62]:
#Преобразование строковых данных в численные
import numpy as np
df['Mileage'] = df['Mileage'].apply(
    lambda x: float(x[0:-4].replace(",", ".")) if isinstance(x, str) and x.endswith(" mi.") else np.nan
)
df['Monthly Payment'] = df['Monthly Payment'].apply(
    lambda x: float(x[6:-3].replace(",", "")) if isinstance(x, str) and x.endswith("/mo") else np.nan
)

In [63]:
#Заполнение численных пропусков средним значением и медианой. А строковые новой строкой
df['Mileage'] = df['Mileage'].fillna(df['Mileage'].mean())
df['Monthly Payment'] = df['Monthly Payment'].fillna(df['Monthly Payment'].median())
df['Condition'] = df['Condition'].fillna("Unknown")

In [64]:
#Удаление дубликатов
df = df.drop_duplicates()
print("Дубликаты удалены.")

Дубликаты удалены.

In [65]:
#Конечное преобразование строковых данных
df['Price (USD)'] = df['Price (USD)'].apply(
    lambda x: float(x[1::].replace(",", "")) if isinstance(x, str) and x.startswith("$") else np.nan
)
df

,Car Model,Condition,Mileage,Price (USD),Monthly Payment,Dealer Name
0,2023 BMW M2 Base,Used,2.49600,63000.0,1184.0,Murgado Ford of Chicago
1,2020 Dodge Charger SXT,Used,98.30200,14995.0,282.0,Blue Sky Auto Sales - Brighton Park
2,2016 Scion iM Base,Used,72.04000,12690.0,239.0,Mcgrath Evanston Subaru
3,2022 Volvo XC60 Recharge Plug-In Hybrid T8 Ins...,Used,31.58000,38998.0,733.0,CarMax Birmingham
4,2012 Mitsubishi Lancer SE,Used,54.19700,9995.0,188.0,Moto Zone Inc.
...,...,...,...,...,...,...
10765,2020 Nissan Maxima 3.5 Platinum,Nissan Certified,68.01000,23500.0,442.0,Glendale Nissan
10766,2025 Mercedes-Benz Sprinter 2500 High Roof,New,61.54672,64356.0,1210.0,Mercedes-Benz of Hoffman Estates
10767,2025 Lexus RX 450h+ Luxury,New,61.54672,77254.0,1452.0,Lexus of Arlington
10769,2024 Volkswagen Tiguan 2.0T SE 4MOTION,Used,9.63900,26769.0,503.0,Bill Jacobs VW
10770,2025 Ford Escape Platinum,New,61.54672,38373.0,721.0,Fair Oaks Ford